<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            'view dashboard',
            'view users',
            'create users',
            'edit users',
            'delete users',
            'manage roles',
            'view companies',
            'create companies',
            'edit companies',
            'delete companies',
            'view branches',
            'create branches',
            'edit branches',
            'delete branches',
            'view departments',
            'create departments',
            'edit departments',
            'delete departments',
            'view positions',
            'create positions',
            'edit positions',
            'delete positions',
            'view employment statuses',
            'create employment statuses',
            'edit employment statuses',
            'delete employment statuses',
            'view employment types',
            'create employment types',
            'edit employment types',
            'delete employment types',
            'view employees',
            'create employees',
            'edit employees',
            'delete employees',
            'view employee movements',
            'create employee movements',
            'view employee documents',
            'create employee documents',
            'delete employee documents',
            'view employee assets',
            'create employee assets',
            'edit employee assets',
            'delete employee assets',
            'view employee education',
            'create employee education',
            'edit employee education',
            'delete employee education',
            'view employee experience',
            'create employee experience',
            'edit employee experience',
            'delete employee experience',
            'view employee reprimands',
            'create employee reprimands',
            'edit employee reprimands',
            'delete employee reprimands',
            'view company documents',
            'create company documents',
            'edit company documents',
            'delete company documents',
            'view identity documents',
            'view financial documents',
            'view contract documents',
            'view disciplinary documents',
            'manage private documents',
            'edit contract probation settings',
            'view announcements',
            'create announcements',
            'edit announcements',
            'delete announcements',
            'publish announcements',
            'view holidays',
            'create holidays',
            'edit holidays',
            'delete holidays',
            'view job levels',
            'create job levels',
            'edit job levels',
            'delete job levels',
            'view shifts',
            'create shifts',
            'edit shifts',
            'delete shifts',
            'view working schedules',
            'create working schedules',
            'edit working schedules',
            'delete working schedules',
            'view attendance settings',
            'create attendance settings',
            'edit attendance settings',
            'delete attendance settings',
            'view approval flows',
            'create approval flows',
            'edit approval flows',
            'delete approval flows',
            'view attendances',
            'create attendances',
            'edit attendances',
            'delete attendances',
            'view attendance devices',
            'create attendance devices',
            'edit attendance devices',
            'delete attendance devices',
            'manage grooming standards',
            'submit grooming store',
            'view grooming self',
            'view grooming store',
            'view attendance requests',
            'create attendance requests',
            'manage absence deductions',
            'view overtime requests',
            'create overtime requests',
            'view change shift requests',
            'create change shift requests',
            'view leave types',
            'create leave types',
            'edit leave types',
            'delete leave types',
            'view leave balances',
            'view leave requests',
            'view salary components',
            'create salary components',
            'edit salary components',
            'delete salary components',
            'view salary structures',
            'create salary structures',
            'edit salary structures',
            'delete salary structures',
            'view employee salaries',
            'create employee salaries',
            'delete employee salaries',
            'view employee allowances',
            'create employee allowances',
            'edit employee allowances',
            'delete employee allowances',
            'view employee deductions',
            'edit employee deductions',
            'create employee deductions',
            'view loans',
            'create loans',
            'edit loans',
            'disburse loans',
            'cancel loans',
            'settle loans',
            'view reimbursements',
            'create reimbursements',
            'cancel reimbursements',
            'disburse reimbursements',
            'manage reimbursement policies',
            'view cash advance policies',
            'create cash advance policies',
            'edit cash advance policies',
            'view cash advance categories',
            'create cash advance categories',
            'edit cash advance categories',
            'delete cash advance categories',
            'view cash advances',
            'create cash advances',
            'cancel cash advances',
            'disburse cash advances',
            'view cash advance approvals',
            'view cash advance settlements',
            'verify cash advance settlements',
            'view cash advance settlements',
            'view expense categories',
            'create expense categories',
            'edit expense categories',
            'delete expense categories',
            'view expense subcategories',
            'create expense subcategories',
            'edit expense subcategories',
            'delete expense subcategories',
            'view expense policies',
            'create expense policies',
            'edit expense policies',
            'view expense claims',
            'create expense claims',
            'cancel expense claims',
            'pay expense claims',
            'view finance reports',
            'export finance reports',
            'view bpjs settings',
            'create bpjs settings',
            'edit bpjs settings',
            'delete bpjs settings',
            'view tax settings',
            'create tax settings',
            'edit tax settings',
            'delete tax settings',
            'view payroll runs',
            'create payroll runs',
            'lock payroll runs',
            'publish payroll runs',
            'request payroll approval',
            'edit payroll settings',
            'manage payroll disbursements',
            'view thr payroll',
            'create thr payroll',
            'edit thr payroll',
            'request thr payroll approval',
            'approve thr payroll',
            'lock thr payroll',
            'publish thr payroll',
            'view non regular payroll',
            'create non regular payroll',
            'edit non regular payroll',
            'request non regular payroll approval',
            'approve non regular payroll',
            'lock non regular payroll',
            'publish non regular payroll',
            'view hiring requisitions',
            'create hiring requisitions',
            'edit hiring requisitions',
            'cancel hiring requisitions',
            'view job vacancies',
            'create job vacancies',
            'edit job vacancies',
            'publish job vacancies',
            'close job vacancies',
            'cancel job vacancies',
            'archive job vacancies',
            'view candidates',
            'hold candidates',
            'select candidates',
            'hire candidates',
            'reconsider candidates',
            'manage candidate blacklist',
            'view offerings',
            'create offerings',
            'edit offerings',
            'send offerings',
            'view screenings',
            'create screenings',
            'decide screenings',
            'view interviews',
            'schedule interviews',
            'conduct interviews',
            'view new joiners',
            'manage new joiners',
            'proceed as employee',
            'view company obligations',
            'create company obligations',
            'edit company obligations',
            'delete company obligations',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission, 'guard_name' => 'web']);
        }

        // Wajib: reset cache registrar SEBELUM syncPermissions,
        // biar tidak baca daftar permission basi dari cache lama.
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $admin = Role::firstOrCreate(['name' => 'admin', 'guard_name' => 'web']);
        $admin->syncPermissions($permissions);

        $hr = Role::firstOrCreate(['name' => 'hr', 'guard_name' => 'web']);
        $hr->syncPermissions([
            'view dashboard',
            'view users',

            // Organization master data yang dibutuhkan HR
            // untuk Hiring Requisition dan employee management.
            'view branches',
            'view departments',
            'view positions',
            'view employment types',

            // Employee core: HR bisa kelola data karyawan sehari-hari.
            'view employees',
            'create employees',
            'edit employees',
            'view employee movements',
            'create employee movements',
            'view employee documents',
            'create employee documents',
            'delete employee documents',
            'view employee assets',
            'create employee assets',
            'edit employee assets',
            'delete employee assets',
            'view employee education',
            'create employee education',
            'edit employee education',
            'delete employee education',
            'view employee experience',
            'create employee experience',
            'edit employee experience',
            'delete employee experience',
            'view employee reprimands',
            'create employee reprimands',
            'edit employee reprimands',
            'delete employee reprimands',
            'view company documents',
            'create company documents',
            'edit company documents',
            'delete company documents',
            'view identity documents',
            'view financial documents',
            'view contract documents',
            'view disciplinary documents',
            'manage private documents',
            'edit contract probation settings',
            'view announcements',
            'create announcements',
            'edit announcements',
            'publish announcements',
            'view hiring requisitions',
            'create hiring requisitions',
            'edit hiring requisitions',
            'cancel hiring requisitions',
            'create job vacancies',
            'view job vacancies',
            'edit job vacancies',
            'publish job vacancies',
            'close job vacancies',
            'cancel job vacancies',
            'archive job vacancies',
            'view candidates',
            'hold candidates',
            'select candidates',
            'hire candidates',
            'reconsider candidates',
            'manage candidate blacklist',
            'view offerings',
            'create offerings',
            'edit offerings',
            'send offerings',
            'view screenings',
            'create screenings',
            'decide screenings',
            'view interviews',
            'schedule interviews',
            'conduct interviews',
            'manage grooming standards',
            'submit grooming store',
            'view grooming self',
            'view grooming store',
            'view attendance requests',
            'create attendance requests',
            'manage absence deductions',
            'view attendances',
            'view overtime requests',
            'view change shift requests',
            'view leave types',
            'view leave balances',
            'view leave requests',
            'view loans',
            'create loans',
            'edit loans',
            'disburse loans',
            'cancel loans',
            'settle loans',
            'view reimbursements',
            'cancel reimbursements',
            'disburse reimbursements',
            'manage reimbursement policies',
            'view cash advance policies',
            'create cash advance policies',
            'edit cash advance policies',
            'view cash advance categories',
            'create cash advance categories',
            'edit cash advance categories',
            'delete cash advance categories',
            'view cash advances',
            'cancel cash advances',
            'disburse cash advances',
            'view cash advance approvals',
            'view cash advance settlements',
            'verify cash advance settlements',
            'view expense categories',
            'create expense categories',
            'edit expense categories',
            'delete expense categories',
            'view expense subcategories',
            'create expense subcategories',
            'edit expense subcategories',
            'delete expense subcategories',
            'view expense policies',
            'create expense policies',
            'edit expense policies',
            'view expense claims',
            'cancel expense claims',
            'pay expense claims',
            'view finance reports',
            'export finance reports',
            'view payroll runs',
            'create payroll runs',
            'request payroll approval',
            'lock payroll runs',
            'publish payroll runs',
            'edit payroll settings',
            'manage payroll disbursements',
            'view thr payroll',
            'create thr payroll',
            'edit thr payroll',
            'request thr payroll approval',
            'approve thr payroll',
            'lock thr payroll',
            'publish thr payroll',
            'view non regular payroll',
            'create non regular payroll',
            'edit non regular payroll',
            'request non regular payroll approval',
            'approve non regular payroll',
            'lock non regular payroll',
            'publish non regular payroll',
            'view new joiners',
            'manage new joiners',
            'proceed as employee',
            'view company obligations',
            'create company obligations',
            'edit company obligations',
            'delete company obligations',
        ]);

        $employee = Role::firstOrCreate(['name' => 'employee', 'guard_name' => 'web']);
        $employee->syncPermissions([
            'view dashboard',
            'create hiring requisitions',
            'create employee movements',
            'create attendance requests',
            'create overtime requests',
            'create change shift requests',
            'view shifts',
            'create reimbursements',
            'create cash advances',
            'view cash advance policies',
            'create expense claims',
            'view expense categories',
            'view expense subcategories',
        ]);
    }
}